# OpenTelemetry Operator Helm Values
# Generated by Terraform templatefile() — do not edit directly.

# Number of operator controller-manager replicas.
# >= 2 enables leader-election HA.
replicaCount: ${operator_replicas}

manager:
  # Default collector image the Operator uses when creating OpenTelemetryCollector CRDs.
  collectorImage:
    repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
    tag: "${operator_image_tag}"

  # Auto-instrumentation images pinned to stable versions.
  autoInstrumentationImage:
    nodejs:
      repository: ${nodejs_image_repository}
      tag: "${nodejs_image_tag}"

  # Operator controller-manager resources.
  resources:
    requests:
      cpu: "${operator_resources_requests_cpu}"
      memory: "${operator_resources_requests_memory}"
    limits:
      cpu: "${operator_resources_limits_cpu}"
      memory: "${operator_resources_limits_memory}"

  # Leader election — required when replicaCount > 1.
  leaderElection:
    enabled: true

# cert-manager integration for webhook TLS certificate issuance and rotation.
# Requires cert-manager to be installed in the cluster before this chart.
admissionWebhooks:
  certManager:
    enabled: true

# Node placement — inherit from environment node_selector.
%{ if length(node_selector) > 0 ~}
nodeSelector:
%{ for k, v in node_selector ~}
  ${k}: "${v}"
%{ endfor ~}
%{ endif ~}
